apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: commit-org1-allchannel-supplychain1-1
  namespace: org1-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: commit-org1-allchannel-supplychain1-1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-devlope
        namespace: flux-devlope
      chart: platforms/hyperledger-fabric/charts/commit_chaincode
  values:
    metadata:
      namespace: org1-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.org1-net:7051
      localmspid: org1MSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://52.12.140.247:8200
      authpath: devlopeorg1-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/org1-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/org1-net/orderer
      secretpath: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.ordererorg-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.2
      name: supplychain
      version: 1
      sequence: 1
      commitarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel
    endorsers:
      creator: org1-net
      name:  org1  org2 
      corepeeraddress:  peer0.org1-net:7051  peer0.org2-net:7051 
      nameslist: 
        - name: org1
        - name: org2
