apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joinchannel-peer0-join-orgchannel-org1-peer0
  namespace: org1-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: joinchannel-peer0-join-orgchannel-org1-peer0
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-devlope
        namespace: flux-devlope
      chart: platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: org1-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.org1-net:7051
      localmspid: org1MSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://54.185.72.226:8200
      authpath: devlopeorg1-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/org1-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/org1-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: orgchannel      
    orderer:
      address: orderer1.ordererorg-net:7050
