apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: org1-peer0
  namespace: org1-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: org1-peer0
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-devlope
        namespace: flux-devlope
      chart: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: org1-net
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        
    peer:
      name: peer0
      gossippeeraddress: peer0.org1-net:7051
      gossipexternalendpoint: peer0.org1-net:7051
      localmspid: org1MSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.2
      couchdb:
        username: org1-user

    storage:
      peer:
        storageclassname: org1sc
        storagesize: 512Mi
      couchdb:
        storageclassname: org1sc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://52.12.140.247:8200
      authpath: devlopeorg1-net-auth
      secretprefix: secretsv2/data/crypto/peerOrganizations/org1-net/peers/peer0.org1-net
      secretambassador: secretsv2/data/crypto/peerOrganizations/org1-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secretsv2/data/credentials/org1-net/couchdb/org1?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "none"
      external_url_suffix: none

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
